// Fetches the published Google Sheet CSV and regenerates src/data/guests.ts
// Run locally: SHEETS_CSV_URL=<url> node scripts/sync-guests.mjs
// In CI: set SHEETS_CSV_URL as a GitHub secret

import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const url = process.env.SHEETS_CSV_URL;
if (!url) {
  console.error('Error: SHEETS_CSV_URL environment variable is not set.');
  console.error('  Locally:  SHEETS_CSV_URL=<url> node scripts/sync-guests.mjs');
  console.error('  CI:       add SHEETS_CSV_URL as a GitHub Actions secret');
  process.exit(1);
}

console.log('Fetching guest list from Google Sheets...');
const res = await fetch(url);
if (!res.ok) {
  console.error(`Failed to fetch sheet: ${res.status} ${res.statusText}`);
  process.exit(1);
}

const csv = await res.text();
const lines = csv.trim().split('\n');
const headers = lines[0].split(',').map(h => h.trim().toLowerCase());
const rows = lines.slice(1).filter(r => r.trim());

function col(cols, key) {
  return (cols[headers.indexOf(key)] ?? '').trim();
}

const guests = rows
  .map(row => {
    const cols = row.split(',');
    return {
      id:         parseInt(col(cols, 'id'), 10),
      name:       col(cols, 'name'),
      phone:      col(cols, 'phone'),
      gender:     col(cols, 'gender').toLowerCase(),
      inviteType: col(cols, 'invitetype'),
      count:      parseInt(col(cols, 'count'), 10) || 1,
    };
  })
  .filter(g => !isNaN(g.id) && g.name);

const ts = `// AUTO-GENERATED by scripts/sync-guests.mjs — do not edit manually
export interface Guest {
  id: number;
  name: string;
  phone: string;
  gender: 'male' | 'female';
  inviteType: 'Individual' | 'Individual - Married' | 'Couple' | 'Family';
  count: number;
}

export const guests: Guest[] = ${JSON.stringify(guests, null, 2)};

export function getGuestByToken(token: string): Guest | null {
  try {
    const padded = token + '='.repeat((4 - (token.length % 4)) % 4);
    const decoded = atob(padded);
    const parts = decoded.split(':');
    if (parts[0] === 'w') {
      const id = parseInt(parts[1], 10);
      return guests.find(g => g.id === id) ?? null;
    }
  } catch {
    // invalid token
  }
  return null;
}
`;

const outPath = resolve(__dirname, '../src/data/guests.ts');
writeFileSync(outPath, ts, 'utf8');
console.log(`Done — ${guests.length} guests written to src/data/guests.ts`);
